spring.application.name=vote-aggregator

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

server.port=8081

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:vote-aggregator
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=enzo
spring.datasource.password=
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
