spring.application.name=spy
spring.jpa.defer-datasource-initialization=true

#spring.security.user.name=enzo
#spring.security.user.password=123456

# RSA KEYS
rsa.private-key=classpath:keys/private_key.pem
rsa.public-key=classpath:keys/public_key.pem